apiVersion: v1
kind: Secret
metadata:
  name: test-app
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.com/infrastructure-as-code5/infrastructure.git
  password: 3p4MGtXAk3sYwQDDXQrp
  username: gitlab+deploy-token-957909

---  

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/infrastructure-as-code5/infrastructure.git
    targetRevision: main
    path: argocd/argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
