plan-development:
  stage: plan
  environment:
    name: development
  variables:
    ENVIRONMENT_NAME: dev
  allow_failure: false
  extends: .terraform_plan
  needs: ["validate","format"]

apply-development:
  stage: apply
  environment:
    name: development
  variables:
    ENVIRONMENT_NAME: dev
  allow_failure: false
  extends: .terraform_apply   
  rules:
    - when: manual

destroy-development:
  stage: destroy
  environment:
    name: development
  variables:
    ENVIRONMENT_NAME: dev
  allow_failure: false
  extends: .terraform_destroy  
  rules:       
    - when: manual