- hosts: master[0]
  roles:
    - cloudflare
  vars:
    DNS:
      - {record: 'bitwarden', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'nextcloud', zone: 'durp.info', proxied: 'yes', state: 'present'} 
      - {record: 'grafana', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'kong', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: '@', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'whoogle', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'kuma', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'oauth', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'kasm', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'nexus', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'docker', zone: 'durp.info', proxied: 'yes', state: 'present'}
      - {record: 'authentik', zone: 'durp.info', proxied: 'yes', state: 'present'}
