- hosts: all
  gather_facts: true
  become: true
  roles:
    - base

- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - k3s/prereq
    - k3s/download

- hosts: master
  become: true
  roles:
    - k3s/master

- hosts: node
  become: true
  roles:
    - k3s/node

- hosts: master
  become: true
  roles:
    - role: k3s/post

- hosts: master[0]
  become: true
  roles:
    - k3s/argocd
