---
required_packages:
    - ufw
    - qemu-guest-agent
    - fail2ban
    - unattended-upgrades
    - cockpit
    - nfs-common
    - open-iscsi

redhat_required_packages:
    - qemu-guest-agent
    - cockpit     
    - iscsi-initiator-utils 
    - powershell

unnecessary_services:
    - postfix
    - telnet
    
unnecessary_software:
    - tcpdump
    - nmap-ncat
    - wpa_supplicant    

redhat_required_repositories:
    - {baseurl: 'https://packages.microsoft.com/rhel/8/prod/', name: 'Microsoft', gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'}    
