---
required_packages:
    - ufw
    - qemu-guest-agent
    - fail2ban
    - unattended-upgrades
    - cockpit
    - nfs-common
    - open-iscsi
    - powershell

redhat_required_packages:
    - qemu-guest-agent
    - cockpit     
    - iscsi-initiator-utils 

unnecessary_services:
    - postfix
    - telnet
    
unnecessary_software:
    - tcpdump
    - nmap-ncat
    - wpa_supplicant    

redhat_required_repositories:
    - {baseurl: 'https://nexus.durp.info/repository/Microsoft/', name: 'Microsoft', gpgkey: 'https://nexus.durp.info/repository/keys/yum/nexus.asc'}    
