- name: Copy configs
  ansible.builtin.copy:
    src: ./roles/k3s/argocd/templates/
    dest: /opt/argocd
    owner: administrator
    group: administrator
    mode: "0664"
    force: true

- name: Copy configs
  ansible.builtin.copy:
    src: "{{ lookup('env', 'kubeseal') }}"
    dest: /opt/kubeseal.yaml
    owner: administrator
    group: administrator
    mode: "0600"
    force: true

- name: Apply Kubeseal master key
  ansible.builtin.command: k3s kubectl apply -f /opt/kubeseal.yaml --force

- name: Apply ArgoCD
  ansible.builtin.command: k3s kubectl apply -f /opt/argocd/argocd.yaml -n argocd

- name: Apply ArgoCD Apps
  ansible.builtin.command: k3s kubectl apply -f /opt/argocd/apps.yaml -n argocd
  