---
- name: Apply Kubeseal master key
  command: k3s kubectl apply -f kubeseal.yaml --force

- name: Apply ArgoCD namespace
  command: k3s kubectl apply -f https://raw.githubusercontent.com/DeveloperDurp/homelab/main/argocd/namespace.yaml -n argocd

- name: Apply ArgoCD deployment
  command: k3s kubectl apply -f https://raw.githubusercontent.com/DeveloperDurp/homelab/main/argocd/deployment.yaml -n argocd  

- name: Apply ArgoCD Apps
  command: k3s kubectl apply -f https://raw.githubusercontent.com/DeveloperDurp/homelab/main/argocd/apps.yaml -n argocd  

  
